version: "3.3"
services:
  mongodb:
    image: mongo:3.4
    volumes:
      - ./data/db:/data/db # 数据库文件存放地址，根据需要修改为本地地址
  redis:
    image: redis:4.0.6
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data # redis 数据文件存放地址，根据需要修改为本地地址
  web:
    image: easymock/easymock:1.6.0
    command: /bin/bash -c "npm start"
    links:
      - mongodb:mongodb
    ports:
      - 7300:7300
    volumes:
      - ./logs:/home/easy-mock/easy-mock/logs
